### ISSUE TITLE
Exception in Reflectable

### ISSUE THREAD

**Issue by zijam** [dart-lang/sample-todomvc-polymer#13]
When I run the master branch in IntelliJ using Dartium, I get the following error:
```
Exception: 'package:reflectable/src/reflectable_transformer_based.dart': error: line 249 pos 64: unexpected token '.'
        methodName, positionalArguments.length, namedArguments?.keys)) {
```
I'm running dart version 1.13.2.

When I ``` Pub build``` the project and run the example in Chrome there is no exception and the app works. 

Doesn't null-aware operator works in dartium, i'm running Chromium version 39.0.2171.0

**Comment by jakemac53** [comment]
Maybe intellij is launching a different version of dartium than you think? I would try running pub serve on the command line and manually launching dartium on the command line as well, and see if that works.

**Comment by zijam** [comment]
Didn't help, still get the same error in Dartium dev console
```
 Exception: 'package:reflectable/src/reflectable_transformer_based.dart': error: line 249 pos 64: unexpected token '.'
        methodName, positionalArguments.length, namedArguments?.keys)) {
package:polymer/src/common/polymer_mixin.dart:23 
HtmlElement&PolymerMixin.polymerCreatedpackage:polymer/polymer_micro.dart:23 
PolymerElement.PolymerElement.createdpackage:todomvc/td_todos.dart:41 
TodoList.TodoList.createdpackage:web_components/interop.dart:38 
upgradeElementpackage:web_components/interop.dart:41 
registerDartTypepackage:web_components/custom_element_proxy.dart:23 
CustomElementProxy.initializepackage:polymer/src/common/polymer_register.dart:21 
PolymerRegister.initializepackage:initialize/src/static_loader.dart:46 <anonymous closure>package:initialize/initialize.dart:35 
_runInitQueue@902173292package:initialize/initialize.dart:38 <anonymous closure>
```

**Comment by jakemac53** [comment]
How are you launching dartium? How are your verifying your sdk version?

**Comment by zijam** [comment]
I had installed *dart* and *dartium* using Homebrew, but found out that the *dartium* and *content_shell* hadn't been updated since version _1.11.3_, using ```brew upgrade``` command. 
After uninstalling dart and installing dart with dartium and content_shell again, the sample project was running without any exception.

NB: It looks like, only way to find out which version of dartium I was running, was by looking in the dart folder in Homebrew installation path.
